server:
  port: 3000
application:
  domain: aGameWars.op
  name: 'E-Shop'
  logo: elogo.png
  favicon: favicon.ico
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showChallengeHints: false
  showVersionNumber: false
  theme: united
  gitHubRibbon: none
  twitterUrl: 'https://twitter.com/abcloudsec'
  planetOverlayMap: orangemap2k.jpg
  planetName: Orangeuze
  recyclePage:
    topProductImage: undefined.png
    bottomProductImage: undefined.png
  altcoinName: Coolcoin
  cookieConsent:
    backgroundColor: '#eb6c44'
    textColor: '#ffffff'
    buttonColor: '#f5d948'
    buttonTextColor: '#000000'
    message: 'This website uses a myriad of 3rd-party cookies for your convenience and tracking pleasure.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@agame.op'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
products:
  -
    name: 'Zombie Juice (1000ml)'
    price: 1.99
    description: 'The all-time classic.'
    image: apple_juice.jpg
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'E. Corp Hat'
    description: 'Made from real polyester and assembled in a foreign country'
    price: 2.99
    image: e_hat.jpg
  -
    name: 'E. Corp Gym Bag'
    description: 'Now with even more exotic colours!'
    price: 8.99
    image: e_gymbag.jpg
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'E. Corp Travel Mug'
    description: 'Made from blended plastics and shaped in an exotic way.'
    price: 4.99
    image: e_travel_mug.jpg
  -
    name: 'Lemon Juice (500ml)'
    description: 'Sour but full of vitamins.'
    price: 2.99
    image: lemon_juice.jpg
  -
    name: 'Banana Juice (1000ml)'
    description: 'Monkeys love it the most.'
    price: 1.99
    image: banana_juice.jpg
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'E. Corp Shop T-Shirt'
    description: 'Real fans wear it 24/7!'
    price: 22.49
    image: men_shirt.jpg
  -
    name: 'E. Corp Shop Girlie-Shirt'
    description: 'For serious E. Corp heroines only!'
    price: 22.49
    image: women_shirt.jpg
  -
    name: 'OWASP SSL Advanced Forensic Tool (O-Saft)'
    description: 'O-Saft is an easy to use tool to show information about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations.'
    price: 0.01
    image: owasp.jpeg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: undefined.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'E. Corp Shop Sticker (2015/2016 design)'
    description: 'Die-cut sticker with the official 2015/2016 logo. By now this is a rare collectors item. <em>Out of stock!</em>'
    price: 999.99
    image: e_sticker.png
    deletedDate: '2017-04-28'
  -
    name: 'E. Corp Shop Iron-Ons (16pcs)'
    description: 'Upgrade your clothes with washer safe iron on!'
    price: 14.99
    image: e_iron_on.jpg
  -
    name: 'E. Corp Shop Laptop Sticker (16pcs)'
    description: 'Your laptop will be even cooler with these laptop magnets!'
    price: 15.99
    image: e_laptop_sticker.jpg
     reviews:
      - { text: 'I straight-up gots nuff props fo''thingss!', author: mc.safesearch }
  -
    name: 'E. Corp Shop Mug'
    description: 'White mug with corporate logo on it! Your colleagues will envy you!'
    price: 21.99
    image: e_coffee_mug.jpg
  -
    name: 'E. Corp Shop Hoodie'
    description: 'E. Corp apparel. But in black. And with logo.'
    price: 49.99
    image: mens_hoodie.jpg
  -
    name: 'E. Corp Shop Velcro Patch'
    description: '4x3.5" embroidered patch with velcro backside. The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    image: velcro_patch.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: mc.safesearch }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Woodruff Syrup "Forest Master X-Treme"'
    description: 'Harvested and manufactured in the Black Forest, Germany. Can cause hyperactive behavior in children. Can cause permanent green tongue when consumed undiluted.'
    price: 6.99
    image: woodruff_syrup.jpg
  -
    name: 'Green Smoothie'
    description: 'Looks poisonous but is actually very good for your health! Made from green cabbage, spinach, kiwi and grass.'
    price: 1.99
    image: green_smoothie.jpg
    reviews:
      - { text: 'Fresh out of a replicator.', author: jim }
  -
    name: 'Quince Juice (1000ml)'
    description: 'Juice of the <em>Cydonia oblonga</em> fruit. Not exactly sweet but rich in Vitamin C.'
    price: 4.99
    image: quince.jpg
  -
    name: 'Allsafe Shirt'
    description: '(ex) Vendor t-shirt. Can be <a href="/#recycle">sent back to us</a> for recycling.'
    price: 0.89
    image: allsafe_shirt01.jpg
  -
    name: 'Fruit Press'
    description: 'Fruits go in. Juice comes out. Pomace you can send back to us for recycling purposes.'
    price: 89.99
    image: fruit_press.jpg
  -
    name: 'E Corp Shop Thing (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: 'E. Corp Shop Artwork'
    description: 'Unique masterpiece painted with different kinds of lines on 90g/m² lined paper.'
    price: 278.74
    image: e_artwork.jpg
  -
    name: 'Global OWASP WASPY Award 2017 Nomnation'
    description: 'Your chance to nominate up to three quiet pillars of the OWASP community ends 2017-06-30! <a href="https://www.owasp.org/index.php/WASPY_Awards_2017">Nominate now!</a>'
    price: 0.03
    image: waspy.png
    deletedDate: '2017-07-01'
  -
    name: 'Strawberry Juice (500ml)'
    description: 'Sweet & tasty!'
    price: 3.99
    image: strawberry_juice.jpeg
  -
    name: 'Carrot Juice (1000ml)'
    description: 'As the old German saying goes: "Carrots are good for the eyes. Or has anyone ever seen a rabbit with glasses?"'
    price: 2.99
    image: carrot_juice.jpeg
  -
    name: 'E. Corp Tour 2017 Sticker Sheet (Special Edition)'
    description: '10 sheets of themed stickers with 15 stickers on each.'
    price: 19.1
    image: e_stickere.png
    deletedDate: '2017-09-20'
  -
    name: 'E. Corp Laptop Sleave'
    description: 'Awesome new 2018 edition Laptop sleave.'
    price: 2999
    image: e_laptop_sleave.jpeg
ctf:
  countryMapping: ~
  showFlagsInNotifications: true
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  
